results_dir: results # Path to save results
data_dir: data # Path to save data
model_dir: models # Path to save models
log_dir: logs # Path to save logs

evaluator_class: evaluation.EpisodicEvaluator
model_class: teacher.PPOTeacherHeist
model_save_path: /gpfs/u/home/KDRL/KDRLynze/scratch/KDRL/logs/2023-12-04T18-00-15_heist__seed_1/ppo_heist_model_800000_steps
num_episodes: 10

save_name: evaluation10_teacher

defaults:
  - env: heist1
