# config.yaml
results_dir: results # Path to save results
data_dir: data # Path to save data
model_dir: models # Path to save models
log_dir: logs # Path to save logs
student_save_path: null

defaults:
  - _self_
  - env: heist0
  - student: policy_student
  - distill: exp1
  - loss: MAE
  - optimizer: adam0
  - buffer: batch_buffer100
